package_assets: on

javascripts:
  common:    
    - public/javascripts/jquery-1.5.1.min.js
  workspace:

    - public/javascripts/bootstrap-dropdown.js
    - public/javascripts/submit-data.js



stylesheets:
  common:
    - public/stylesheets/*.css
    - public/stylesheets/generated/*.css

